baseURL: https://www.aaroncarson.co.uk/
languageCode: en-gb
title: Aaron Carson
theme: papermod

params:
  profileMode:
    enabled: true
    title: Aaron Carson
    subtitle: Cyber security... amongst other things.
    imageUrl: /images/aaroncarson.png
    imageTitle: Aaron Carson stood in front of Tower Bridge in London.
    buttons:
      - name: About
        url: /about
      - name: Contact
        url: /contact
      - name: Posts
        url: /posts
  socialIcons:
    - name: twitter
      url: https://twitter.com/acar321
    - name: linkedin
      url: https://www.linkedin.com/in/aaron-carson
  comments: true
